apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-1
  labels:
    cni: calico
spec:
  topology:
    class: lennart-metal3-v0.1.0
    version: v1.34.1
    variables:
    - name: controlPlaneEndpoint
      value:
        host: 192.168.222.100
    - name: imageName
      value: ubuntu-2404
    - name: addImageVersion
      value: false
    - name: imageChecksum
      value: cb0ba1e5a579188fabab89a6745891ce8752aef926ffa70ec59b8570fbb7725e
    - name: injectSetupScripts
      value: true
    - name: users
      value:
      - name: ubuntu
        sudo: 'ALL=(ALL) NOPASSWD:ALL'
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOxg0/L9LWM8K6//pe5OYc7SK4vv6676uz6VRJGA44nl lennart
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
