apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-1
  labels:
    cni: calico
spec:
  topology:
    class: lennart-metal3-v0.1.0
    version: v1.32.1
    variables:
    - name: imageChecksum
      value: cb0ba1e5a579188fabab89a6745891ce8752aef926ffa70ec59b8570fbb7725e
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
