apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
          # - name: containerdisk
          #   disk:
          #     bus: virtio
          - name: emptydisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            bridge: {}
          - name: metal3
            bridge: {}
            macAddress: 00:60:2f:31:81:10
            bootOrder: 1
        resources:
          requests:
            memory: 2048M
      networks:
      - name: default
        pod: {}
      - name: metal3
        hostBridge:
          bridgeName: metal3
      volumes:
      # - name: containerdisk
      #   containerDisk:
      #     image: quay.io/kubevirt/cirros-container-disk-demo
      - name: emptydisk
        emptyDisk:
          capacity: 20Gi
