apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- calico
- cloud-provider-openstack
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- files:
  - cloud.conf
  - clouds.yaml
  name: cloud-config
  namespace: kube-system
  type: Opaque
