apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: lennart-test
spec:
  topology:
    class: lennart-openstack-v0.1.0
    version: v1.28.1
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
