apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: lennart-test
spec:
  topology:
    class: lennart-openstack-v0.1.0
    version: v1.28.3
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: lennart-test-md-unhealthy-5m
spec:
  # clusterName is required to associate this MachineHealthCheck with a particular cluster
  clusterName: lennart-test
  # selector is used to determine which Machines should be health checked
  selector:
    matchLabels:
      topology.cluster.x-k8s.io/deployment-name: md-0
  # Conditions to check on Nodes for matched Machines, if any condition is matched for the duration of its timeout, the Machine is considered unhealthy
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: 300s
  - type: Ready
    status: "False"
    timeout: 300s
