apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: in-memory-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  topology:
    class: in-memory-quick-start
    controlPlane:
      replicas: 1
    version: v1.28.1
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 0
