apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argocd
    repoURL: https://github.com/lentzi90/playground.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
