apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/kustomizations/capi-operator
    repoURL: https://github.com/lentzi90/playground.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
