apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
# - https://github.com/kubernetes-sigs/cluster-api/hack/observability/visualizer

helmCharts:
  - name: cluster-api-visualizer
    repo: https://jont828.github.io/cluster-api-visualizer/charts
    releaseName: visualizer
    namespace: observability
    valuesFile: values.yaml
    version: 1.2.0
