---
apiVersion: v1
kind: Secret
metadata:
  name: user-data-04
type: Opaque
stringData:
  value: |
    #cloud-config
    users:
    - name: ubuntu
      sudo: 'ALL=(ALL) NOPASSWD:ALL'
      lock_passwd: False
      plain_text_passwd: 'password'
      # ssh_import_id:
      # - gh:lentzi90
      ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3XsjgwkAkxd5aioPiBws7O5nx5ofcR4TvAIOvSQ9Ce lennart.jern@est.tech

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bml-04
spec:
  online: true
  bootMACAddress: 00:60:2f:31:81:04
  bootMode: UEFI
  bmc:
    address: redfish-virtualmedia+http://192.168.222.1:8000/redfish/v1/Systems/bmh-vm-04
    credentialsName: bml-04
  image:
    checksumType: sha256
    checksum: http://192.168.222.1/SHA256SUMS
    format: qcow2
    url: http://192.168.222.1/jammy-server-cloudimg-amd64.img
  rootDeviceHints:
    deviceName: /dev/vda
  userData:
    name: user-data-04
    namespace: default
