apiVersion: v1
kind: Secret
metadata:
  name: bml-01
type: Opaque
stringData:
  username: replaceme
  password: replaceme
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bml-01
spec:
  online: true
  bootMACAddress: 00:60:2f:31:81:01
  bootMode: legacy
  bmc:
    address: redfish-virtualmedia+http://192.168.222.1:8000/redfish/v1/Systems/bmh-vm-01
    credentialsName: bml-01
  rootDeviceHints:
    deviceName: /dev/vda
---
apiVersion: v1
kind: Secret
metadata:
  name: bml-02
type: Opaque
stringData:
  username: replaceme
  password: replaceme
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bml-02
spec:
  online: true
  bootMACAddress: 00:60:2f:31:81:02
  bootMode: legacy
  bmc:
    address: redfish-virtualmedia+http://192.168.222.1:8000/redfish/v1/Systems/bmh-vm-02
    credentialsName: bml-02
  rootDeviceHints:
    deviceName: /dev/vda
---
apiVersion: v1
kind: Secret
metadata:
  name: bml-03
type: Opaque
stringData:
  username: replaceme
  password: replaceme
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bml-03
spec:
  online: true
  bootMACAddress: 00:60:2f:31:81:03
  bootMode: legacy
  bmc:
    address: redfish-virtualmedia+http://192.168.222.1:8000/redfish/v1/Systems/bmh-vm-03
    credentialsName: bml-03
  rootDeviceHints:
    deviceName: /dev/vda
---
apiVersion: v1
kind: Secret
metadata:
  name: bml-04
type: Opaque
stringData:
  username: replaceme
  password: replaceme
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bml-04
spec:
  online: true
  bootMACAddress: 00:60:2f:31:81:04
  bootMode: UEFI
  bmc:
    address: redfish-virtualmedia+http://192.168.222.1:8000/redfish/v1/Systems/bmh-vm-04
    credentialsName: bml-04
  rootDeviceHints:
    deviceName: /dev/vda
