---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: lennart-openstack-v0.1.0
spec:
  template:
    spec:
      flavor: 4C-4GB-100GB
      identityRef:
        cloudName: lennart-test-fra1
        name: lennart-test-cloud-config
      image:
        filter:
          name: ubuntu-2204-kube
      sshKeyName: lennart-ed25519
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: lennart-openstack-v0.1.0-default-worker
spec:
  template:
    spec:
      flavor: 4C-4GB-100GB
      identityRef:
        cloudName: lennart-test-fra1
        name: lennart-test-cloud-config
      image:
        filter:
          name: ubuntu-2204-kube
      sshKeyName: lennart-ed25519
