apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackClusterTemplate
metadata:
  name: lennart-openstack-v0.1.0
spec:
  template:
    spec:
      apiServerLoadBalancer:
        enabled: true
        allowedCidrs:
        - 10.6.0.0/24
        - 91.150.31.32/32
      cloudName: lennart-test-fra1
      dnsNameservers:
      - 8.8.8.8
      externalNetworkId: fba95253-5543-4078-b793-e2de58c31378
      identityRef:
        kind: Secret
        name: lennart-test-cloud-config
      managedSecurityGroups: true
      nodeCidr: 10.6.0.0/24
      bastion:
        enabled: true
        instance:
          cloudName: lennart-test-fra1
          flavor: 1C-2GB-50GB
          image: "Ubuntu 22.04 Jammy Jellyfish x86_64"
          sshKeyName: lennart-ed25519
