---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackMachineTemplate
metadata:
  name: lennart-openstack-v0.1.0
spec:
  template:
    spec:
      cloudName: lennart-test-kna1
      flavor: 4C-4GB-100GB
      identityRef:
        kind: Secret
        name: lennart-test-cloud-config
      image: ubuntu-2204-kube
      sshKeyName: lennart-ed25519
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackMachineTemplate
metadata:
  name: lennart-openstack-v0.1.0-default-worker
spec:
  template:
    spec:
      cloudName: lennart-test-kna1
      flavor: 4C-4GB-100GB
      identityRef:
        kind: Secret
        name: lennart-test-cloud-config
      image: ubuntu-2204-kube
      sshKeyName: lennart-ed25519
