apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: haos
spec:
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  source:
    http:
      url: "https://github.com/home-assistant/operating-system/releases/download/15.2/haos_ova-15.2.qcow2.xz"
