apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: kamaji-kubevirt
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.243.0.0/16
    services:
      cidrBlocks:
      - 10.95.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KamajiControlPlane
    name: kamaji-kubevirt
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: KubevirtCluster
    name: kamaji-kubevirt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: kamaji-kubevirt
spec:
  controlPlaneEndpoint:
    host: 192.168.0.150
    port: 6443
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: kamaji-kubevirt
spec:
  dataStoreName: default
  dataStoreSchema: kamaji-kubevirt
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
    - ExternalIP
    - InternalIP
    - Hostname
  addons:
    coreDNS: {}
    kubeProxy: {}
  network:
    serviceType: LoadBalancer
    serviceAnnotations:
      metallb.io/loadBalancerIPs: "192.168.0.150"
  deployment:
  replicas: 2
  version: 1.32.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: kamaji-kubevirt-md-0
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: ssh
      virtualMachineTemplate:
        metadata:
          namespace: default
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 2
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: containervolume
                  networkInterfaceMultiqueue: true
                memory:
                  guest: 4Gi
              evictionStrategy: External
              volumes:
              - containerDisk:
                  image: quay.io/capk/ubuntu-2404-container-disk:v1.32.1
                name: containervolume
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: kamaji-kubevirt-md-0
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: kamaji-kubevirt-md-0
spec:
  clusterName: kamaji-kubevirt
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: kamaji-kubevirt-md-0
      clusterName: kamaji-kubevirt
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: KubevirtMachineTemplate
        name: kamaji-kubevirt-md-0
      version: v1.32.1
