apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: lennart-metal3-v0.1.0
spec:
  template:
    spec:
      kubeadmConfigSpec:
        joinConfiguration:
          controlPlane: {}
          nodeRegistration:
            name: '{{ ds.meta_data.name }}'
            kubeletExtraArgs:
              node-labels: 'metal3.io/uuid={{ ds.meta_data.uuid }}'
        initConfiguration:
          nodeRegistration:
            name: '{{ ds.meta_data.name }}'
            kubeletExtraArgs:
              node-labels: 'metal3.io/uuid={{ ds.meta_data.uuid }}'
        users:
          - name: ubuntu
            sudo: 'ALL=(ALL) NOPASSWD:ALL'
            sshAuthorizedKeys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3XsjgwkAkxd5aioPiBws7O5nx5ofcR4TvAIOvSQ9Ce lennart
