apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3ClusterTemplate
metadata:
  name: lennart-metal3-v0.1.0
spec:
  template:
    spec:
      controlPlaneEndpoint:
        host: 192.168.222.100
        port: 6443
      noCloudProvider: true
