apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: kubevirt-test-1-controlplane-template
  namespace: default
spec:
  clusterName: kubevirt-test-1
  metaData:
    objectNames:
    - key: machine_name
      object: machine
    - key: metal3machine_name
      object: metal3machine
    - key: bmh_name
      object: baremetalhost
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: kubevirt-test-1-workers-template
  namespace: default
spec:
  clusterName: kubevirt-test-1
  metaData:
    objectNames:
    - key: machine_name
      object: machine
    - key: metal3machine_name
      object: metal3machine
    - key: bmh_name
      object: baremetalhost
