apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: kamaji-metal3
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 192.168.0.150
    port: 6443
  noCloudProvider: true
