apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: kamaji-metal3-workers-template
  namespace: default
spec:
  clusterName: kamaji-metal3
  metaData:
    objectNames:
    - key: name
      object: machine
    - key: local-hostname
      object: machine
    - key: local_hostname
      object: machine
    ipAddressesFromIPPool:
    - key: internal_ip
      name: internal-kamaji-metal3
  networkData:
    links:
      ethernets:
      - type: phy
        id: eno49
        macAddress:
          fromHostInterface: eno49
          # fromHostInterface: ens5f0np0
      vlans:
      - id: eno49.5
        vlanID: 5
        macAddress:
          fromHostInterface: eno49
          # fromHostInterface: ens5f0np0
        vlanLink: eno49
    networks:
      ipv4:
      - id: kcp
        link: eno49
        ipAddressFromIPPool: internal-kamaji-metal3
        routes:
        - network: 192.168.0.0
          prefix: 24
          gateway:
            fromIPPool: internal-kamaji-metal3
      - id: external
        link: eno49.5
        ipAddressFromIPPool: external-ipv4-kamaji-metal3
        routes:
        - network: 0.0.0.0
          prefix: 0
          gateway:
            fromIPPool: external-ipv4-kamaji-metal3
    services:
      dns:
      - 8.8.8.8
      - 1.1.1.1
