apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: kamaji-metal3-ubuntu
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      hostSelector:
        matchLabels:
          # bmh-name: eselda13u31s04
          # bmh-name: eselda13u31s06
          # bmh-name: eselda13u31s14
          bmh-name: eseldb12u11
      dataTemplate:
        name: kamaji-metal3-ubuntu
      image:
        checksum: 9611c5a9d6c43e60090305c58a1aeb5d9f1f0c0bec409004185e6284755322d1
        checksumType: sha256
        format: qcow2
        url: http://192.168.0.1/ubuntu-2404.img
