apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ubuntu
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: kamaji-metal3
spec:
  clusterName: kamaji-metal3
  replicas: 1
  selector:
    matchLabels:
      machinedeployment: ubuntu
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        machinedeployment: ubuntu
        cluster.x-k8s.io/cluster-name: kamaji-metal3
    spec:
      nodeDrainTimeout: "0s"
      clusterName: kamaji-metal3
      version: v1.33.1
      bootstrap:
        configRef:
          name: kamaji-metal3-ubuntu
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: kamaji-metal3-ubuntu
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
