apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: kamaji-metal3-ubuntu
  namespace: default
spec:
  template:
    spec:
      files:
      - contentFrom:
          secret:
            key: ubuntu-install-k8s-release-artifacts.sh
            name: install-k8s
        path: /tmp/install-k8s.sh
        owner: root:root
        permissions: '0755'
      preKubeadmCommands:
      - echo "127.0.1.1 {{ ds.meta_data.name }}" >> /etc/hosts
      - /tmp/install-k8s.sh
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.name }}'
          kubeletExtraArgs:
            node-labels: 'metal3.io/uuid={{ ds.meta_data.uuid }}'
            node-ip: '{{ ds.meta_data.internal_ip }}'
      users:
      - name: ubuntu
        sudo: 'ALL=(ALL) NOPASSWD:ALL'
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOxg0/L9LWM8K6//pe5OYc7SK4vv6676uz6VRJGA44nl lennart
