apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: k3s-1
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 10.96.0.0/12
    pods:
      cidrBlocks:
      - 192.168.0.0/18
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: Metal3Cluster
    name: k3s-1
  controlPlaneRef:
    kind: KThreesControlPlane
    apiGroup: controlplane.cluster.x-k8s.io
    name: k3s-1
