apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: k3s-1
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 192.168.222.104
    port: 6443
  noCloudProvider: true
