apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: k3s-1-controlplane-template
  namespace: default
spec:
  clusterName: k3s-1
  metaData:
    gatewaysFromIPPool:
    - apiGroup: ipam.metal3.io
      key: Gateway_For_Net_ipv4
      kind: IPPool
      name: control-plane-endpoint-k3s-1
    indexes:
    - key: machine_index
      step: 1
    ipAddressesFromIPPool:
    - apiGroup: ipam.metal3.io
      key: IP_For_Net_ipv4
      kind: IPPool
      name: control-plane-endpoint-k3s-1
    objectNames:
    - key: machine_name
      object: machine
    - key: metal3machine_name
      object: metal3machine
    - key: bmh_name
      object: baremetalhost
    prefixesFromIPPool:
    - apiGroup: ipam.metal3.io
      key: Prefix_For_Net_ipv4
      kind: IPPool
      name: control-plane-endpoint-k3s-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: k3s-1-workers-template
  namespace: default
spec:
  clusterName: k3s-1
  metaData:
    gatewaysFromIPPool:
    - apiGroup: ipam.metal3.io
      key: Gateway_For_Net_ipv4
      kind: IPPool
      name: netpool-ipv4-k3s-1
    indexes:
    - key: machine_index
      step: 1
    ipAddressesFromIPPool:
    - apiGroup: ipam.metal3.io
      key: IP_For_Net_ipv4
      kind: IPPool
      name: netpool-ipv4-k3s-1
    objectNames:
    - key: machine_name
      object: machine
    - key: metal3machine_name
      object: metal3machine
    - key: bmh_name
      object: baremetalhost
    prefixesFromIPPool:
    - apiGroup: ipam.metal3.io
      key: Prefix_For_Net_ipv4
      kind: IPPool
      name: netpool-ipv4-k3s-1
  templateReference: k3s-1-workers
