apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: lennart-openstack-v0.1.0
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: lennart-openstack-v0.1.0
      namespace: default
    machineInfrastructure:
      ref:
        kind: OpenStackMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: lennart-openstack-v0.1.0
        namespace: default
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackClusterTemplate
      name: lennart-openstack-v0.1.0
      namespace: default
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: lennart-openstack-v0.1.0-default-worker
            namespace: default
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: OpenStackMachineTemplate
            name: lennart-openstack-v0.1.0-default-worker
            namespace: default

  variables:
  - name: identityRef
    required: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          name:
            type: string
            description: "The name of the OpenStackCloudConfigSecret."
          cloudName:
            type: string
            description: "The name of the cloud in the OpenStackCloudConfigSecret."
  patches:
  - name: image
    description: "Sets the OpenStack image that is used for creating the servers."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/filter/name
        valueFrom:
          template: |
            ubuntu-2204-kube-{{ .builtin.controlPlane.version }}
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/filter/name
        valueFrom:
          template: |
            ubuntu-2204-kube-{{ .builtin.machineDeployment.version }}
  - name: identityRef
    description: "Sets the OpenStack identity reference."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/identityRef
        valueFrom:
          variable: identityRef
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/identityRef
        valueFrom:
          variable: identityRef
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/identityRef
        valueFrom:
          variable: identityRef
