apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- capo-class.yaml
- kubeadmconfigtemplate.yaml
- kubeadmcontrolplanetemplate.yaml
- openstackclustertemplate.yaml
- openstackmachinetemplates.yaml

generatorOptions:
  disableNameSuffixHash: true
