---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: lennart-openstack-v0.1.0
spec:
  template:
    spec:
      flavor: c4m4
      image:
        filter:
          name: ubuntu-2204-kube
      rootVolume:
        sizeGiB: 100
      sshKeyName: lennart-ed25519
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: lennart-openstack-v0.1.0-default-worker
spec:
  template:
    spec:
      flavor: c4m4
      image:
        filter:
          name: ubuntu-2204-kube
      rootVolume:
        sizeGiB: 100
      sshKeyName: lennart-ed25519
