apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackClusterTemplate
metadata:
  name: lennart-openstack-v0.1.0
spec:
  template:
    spec:
      apiServerLoadBalancer:
        allowedCIDRs:
        - 10.6.0.0/24
        enabled: true
      identityRef:
        cloudName: name-of-cloud
        name: secret-name
      managedSecurityGroups:
        allNodesSecurityGroupRules:
        - description: Created by cluster-api-provider-openstack API conversion - BGP (calico)
          direction: ingress
          etherType: IPv4
          name: BGP (calico)
          portRangeMax: 179
          portRangeMin: 179
          protocol: tcp
          remoteManagedGroups:
          - controlplane
          - worker
        - description: Created by cluster-api-provider-openstack API conversion - IP-in-IP (calico)
          direction: ingress
          etherType: IPv4
          name: IP-in-IP (calico)
          protocol: "4"
          remoteManagedGroups:
          - controlplane
          - worker
        allowAllInClusterTraffic: false
      managedSubnets:
      - cidr: 10.6.0.0/24
        dnsNameservers:
        - 8.8.8.8
