apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: metal3-k8s
  labels:
    cni: calico
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 10.96.0.0/12
    pods:
      cidrBlocks:
      - 192.168.64.0/18
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: Metal3Cluster
    name: metal3-k8s
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiGroup: controlplane.cluster.x-k8s.io
    name: metal3-k8s
