apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metal3-class.yaml
- kubeadmconfigtemplate.yaml
- kubeadmcontrolplanetemplate.yaml
- metal3clustertemplate.yaml
- metal3machinetemplates.yaml
- metal3datatemplate.yaml
- ippool.yaml

generatorOptions:
  disableNameSuffixHash: true
