apiVersion: cluster.x-k8s.io/v1beta2
kind: ClusterClass
metadata:
  name: lennart-metal3-v0.1.0
spec:
  controlPlane:
    templateRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: KubeadmControlPlaneTemplate
      name: lennart-metal3-v0.1.0
    machineInfrastructure:
      templateRef:
        kind: Metal3MachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: lennart-metal3-v0.1.0
  infrastructure:
    templateRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3ClusterTemplate
      name: lennart-metal3-v0.1.0
  workers:
    machineDeployments:
    - class: default-worker
      bootstrap:
        templateRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
          kind: KubeadmConfigTemplate
          name: lennart-metal3-v0.1.0-default-worker
      infrastructure:
        templateRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: Metal3MachineTemplate
          name: lennart-metal3-v0.1.0-default-worker
  variables:
  - name: controlPlaneEndpoint
    required: false
    schema:
      openAPIV3Schema:
        type: object
        description: "The control plane endpoint configuration"
        properties:
          host:
            type: string
            description: "The host IP address for the control plane endpoint"
            default: "192.168.222.100"
          port:
            type: integer
            description: "The port number for the control plane endpoint"
            default: 6443
  - name: imageName
    required: false
    schema:
      openAPIV3Schema:
        type: string
        description: |
          The base name of the disk image that is used for provisioning the servers.
          If addImageVersion this will be combined with the k8s version to create the full name.
          E.g. imageName-v1.31.2.
        default: "ubuntu-2404-kube"
  - name: imageChecksum
    required: true
    schema:
      openAPIV3Schema:
        type: string
        example: aab4cbba9707d14c58931f6e9fb75736d5fe3df0f52a4e19c70609e11b5623af
        description: "The checksum of the image to use for the servers."
  - name: addImageVersion
    required: false
    schema:
      openAPIV3Schema:
        type: boolean
        description: |
          Add a suffix with the Kubernetes version to the imageName. E.g. imageName-v1.32.2.
        default: true
  - name: injectSetupScripts
    required: false
    schema:
      openAPIV3Schema:
        type: boolean
        description: |
          Use a sysext overlay to add the Kubernetes components to the image.
          This is for use with flatcar and similar images.
        default: false
  - name: injectKubeVip
    required: false
    schema:
      openAPIV3Schema:
        type: boolean
        description: |
          Use Kube-VIP to provide a virtual IP for the control plane.
        default: true
  - name: users
    required: false
    schema:
      openAPIV3Schema:
        type: array
        description: "List of users to create on the nodes with their SSH keys and sudo access"
        items:
          type: object
          properties:
            name:
              type: string
            sudo:
              type: string
            sshAuthorizedKeys:
              type: array
              items:
                type: string
          required:
          - name
  - name: workerDataTemplateName
    required: false
    schema:
      openAPIV3Schema:
        type: string
        example: test-1-workers-template
        description: "The name of the Metal3DataTemplate to use for the workers."
  - name: controlPlaneDataTemplateName
    required: false
    schema:
      openAPIV3Schema:
        type: string
        example: test-1-controlplane-template
        description: "The name of the Metal3DataTemplate to use for the control plane."
  patches:
  - name: controlPlaneEndpoint
    description: "Configure the control plane endpoint host and port"
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3ClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: replace
        path: /spec/template/spec/controlPlaneEndpoint
        valueFrom:
          variable: controlPlaneEndpoint
  - name: image
    description: "Sets the disk image that should be used to provision the servers."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/url
        valueFrom:
          template: |
            http://192.168.222.1/{{ .imageName }}{{ if .addImageVersion }}-{{ .builtin.controlPlane.version }}{{ end }}.raw
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/url
        valueFrom:
          template: |
            http://192.168.222.1/{{ .imageName }}{{ if .addImageVersion }}-{{ .builtin.machineDeployment.version }}{{ end }}.raw
  - name: imageChecksum
    description: "Sets the image checksum from the variable."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/checksum
        valueFrom:
          variable: imageChecksum
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/checksum
        valueFrom:
          variable: imageChecksum
  - name: users
    description: "Configure the users, their SSH keys and sudo access"
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta2
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/users
        valueFrom:
          variable: users
    - selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
        kind: KubeadmConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/users
        valueFrom:
          variable: users
  - name: controlPlaneDataTemplate
    # TODO: Properly support optional Metal3DataTemplate
    enabledIf: "false"
    description: "Sets the Metal3DataTemplate for the control plane"
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/dataTemplate/name
        valueFrom:
          variable: controlPlaneDataTemplateName
  - name: workerDataTemplate
    # TODO: Properly support optional Metal3DataTemplate
    enabledIf: "false"
    description: "Sets the Metal3DataTemplate for workers"
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/dataTemplate/name
        valueFrom:
          variable: workerDataTemplateName
  - name: controlPlaneScriptsAndFiles
    description: "Add scripts, files, and commands for control plane nodes (setup scripts and/or kube-vip)."
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta2
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/preKubeadmCommands
        valueFrom:
          template: |
            {{ if .injectSetupScripts }}
            - KUBERNETES_VERSION={{ .builtin.controlPlane.version }} /tmp/install-k8s.sh
            {{ end }}
            {{ if .injectKubeVip }}
            # See https://github.com/kube-vip/kube-vip/issues/684
            - "sed -i 's#path: /etc/kubernetes/admin.conf#path: /etc/kubernetes/super-admin.conf#' /etc/kubernetes/manifests/kube-vip.yaml"
            {{ end }}
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands
        valueFrom:
          template: |
            {{ if .injectKubeVip }}
            # See https://github.com/kube-vip/kube-vip/issues/684
            - "sed -i 's#path: /etc/kubernetes/super-admin.conf#path: /etc/kubernetes/admin.conf#' /etc/kubernetes/manifests/kube-vip.yaml"
            {{ end }}
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/files
        valueFrom:
          template: |
            {{ if .injectSetupScripts }}
            - contentFrom:
                secret:
                  key: ubuntu-install-k8s-release-artifacts.sh
                  name: install-k8s
              path: /tmp/install-k8s.sh
              owner: root:root
              permissions: '0755'
            {{ end }}
            {{ if .injectKubeVip }}
            - content: |
                apiVersion: v1
                kind: Pod
                metadata:
                  name: kube-vip
                  namespace: kube-system
                spec:
                  containers:
                  - args:
                    - manager
                    env:
                    - name: vip_arp
                      value: "true"
                    - name: port
                      value: "{{ .controlPlaneEndpoint.port }}"
                    - name: vip_nodename
                      valueFrom:
                        fieldRef:
                          fieldPath: spec.nodeName
                    - name: vip_interface
                      value: enp1s0
                    - name: vip_subnet
                      value: "32"
                    - name: dns_mode
                      value: first
                    - name: cp_enable
                      value: "true"
                    - name: cp_namespace
                      value: kube-system
                    - name: vip_leaderelection
                      value: "true"
                    - name: vip_leasename
                      value: plndr-cp-lock
                    - name: vip_leaseduration
                      value: "5"
                    - name: vip_renewdeadline
                      value: "3"
                    - name: vip_retryperiod
                      value: "1"
                    - name: address
                      value: {{ .controlPlaneEndpoint.host }}
                    - name: prometheus_server
                      value: :2112
                    image: ghcr.io/kube-vip/kube-vip:v1.0.0
                    imagePullPolicy: IfNotPresent
                    name: kube-vip
                    securityContext:
                      capabilities:
                        add:
                        - NET_ADMIN
                        - NET_RAW
                        drop:
                        - ALL
                    volumeMounts:
                    - mountPath: /etc/kubernetes/admin.conf
                      name: kubeconfig
                  hostAliases:
                  - hostnames:
                    - kubernetes
                    ip: 127.0.0.1
                  hostNetwork: true
                  volumes:
                  - hostPath:
                      path: /etc/kubernetes/admin.conf
                    name: kubeconfig
              path: /etc/kubernetes/manifests/kube-vip.yaml
              owner: root:root
              permissions: '0644'
            {{ end }}
  - name: workerScriptsAndFiles
    description: "Add scripts and files for worker nodes."
    enabledIf: "{{ .injectSetupScripts }}"
    definitions:
    - selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
        kind: KubeadmConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/files
        valueFrom:
          template: |
            - contentFrom:
                secret:
                  key: ubuntu-install-k8s-release-artifacts.sh
                  name: install-k8s
              path: /tmp/install-k8s.sh
              owner: root:root
              permissions: '0755'
      - op: add
        path: /spec/template/spec/preKubeadmCommands
        valueFrom:
          template: |
            - KUBERNETES_VERSION={{ .builtin.machineDeployment.version }} /tmp/install-k8s.sh
