apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: lennart-metal3-v0.1.0
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: lennart-metal3-v0.1.0
      namespace: default
    machineInfrastructure:
      ref:
        kind: Metal3MachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: lennart-metal3-v0.1.0
        namespace: default
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3ClusterTemplate
      name: lennart-metal3-v0.1.0
      namespace: default
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: lennart-metal3-v0.1.0-default-worker
            namespace: default
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: Metal3MachineTemplate
            name: lennart-metal3-v0.1.0-default-worker
            namespace: default
  variables:
  - name: imageChecksum
    required: true
    schema:
      openAPIV3Schema:
        type: string
        example: aab4cbba9707d14c58931f6e9fb75736d5fe3df0f52a4e19c70609e11b5623af
        description: "The checksum of the image to use for the servers."
  - name: workerDataTemplateName
    required: false
    schema:
      openAPIV3Schema:
        type: string
        example: my-template
        default: test-1-workers-template
        description: "The name of the Metal3DataTemplate to use for the workers."
  - name: controlPlaneDataTemplateName
    required: false
    schema:
      openAPIV3Schema:
        type: string
        example: my-template
        default: test-1-controlplane-template
        description: "The name of the Metal3DataTemplate to use for the control plane."
  patches:
  - name: controlPlaneImage
    description: "Sets the image that is used for creating the servers."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/url
        valueFrom:
          template: |
            http://192.168.222.1/ubuntu-2404-kube-{{ .builtin.controlPlane.version }}.raw
  - name: workerImage
    description: "Sets the image that is used for creating the servers."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/url
        valueFrom:
          template: |
            http://192.168.222.1/ubuntu-2404-kube-{{ .builtin.machineDeployment.version }}.raw
  - name: controlPlaneImageChecksum
    description: "Sets the image checksum from the variable for control plane."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/checksum
        valueFrom:
          variable: imageChecksum
  - name: workerImageChecksum
    description: "Sets the image checksum from the variable for workers."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/checksum
        valueFrom:
          variable: imageChecksum
  - name: controlPlaneDataTemplate
    description: "Sets the Metal3DataTemplate for the control plane"
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/dataTemplate/name
        valueFrom:
          variable: controlPlaneDataTemplateName
  - name: workerDataTemplate
    description: "Sets the Metal3DataTemplate for workers"
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/dataTemplate/name
        valueFrom:
          variable: workerDataTemplateName
