apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: kamaji-1-workers
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      image:
        checksum: cb0ba1e5a579188fabab89a6745891ce8752aef926ffa70ec59b8570fbb7725e
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404.raw
