apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- files:
  - ubuntu-install-k8s.sh
  - ubuntu-sysext-k8s.sh
  - ubuntu-install-k8s-release-artifacts.sh
  - centos-install-k8s-release-artifacts.sh
  name: install-k8s
  namespace: default
