apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinderplugin
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
