apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: lennart-metal3-ubuntu-sysext-v0.1.0
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      image:
        checksum: "0000000000000000000000000000000000000000000000000000000000000000"
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: lennart-metal3-ubuntu-sysext-v0.1.0-default-worker
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      image:
        checksum: "0000000000000000000000000000000000000000000000000000000000000000"
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404.raw
