apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: lennart-workload
  labels:
    cni: calico
    cloud: openstack
spec:
  topology:
    class: lennart-openstack-v0.1.0
    version: v1.28.6
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
