apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: lennart-workload
  labels:
    cni: calico
    cloud: openstack
spec:
  topology:
    class: lennart-openstack-v0.1.0
    version: v1.31.1
    variables:
      - name: identityRef
        value:
          name: lennart-test-cloud-config
          cloudName: xerces-capo
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
