apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: lennart-workload
  labels:
    cni: calico
    cloud: openstack
spec:
  topology:
    classRef:
      name: lennart-openstack-v0.1.0
      namespace: default
    version: v1.34.0
    variables:
    - name: identityRef
      value:
        name: lennart-test-cloud-config
        cloudName: xerces-capo
    - name: imageName
      value: "Ubuntu-24.04"
    - name: addImageVersion
      value: false
    - name: injectSetupScripts
      value: true
    - name: bastion
      value:
        enabled: false
        spec:
          flavor: c1m2-est
          image:
            # id: 19e017ae-2759-479c-90ac-a400a3f64678
            filter:
              name: Ubuntu-24.04
          sshKeyName: lennart-ed25519
    - name: allowedCIDRs
      value:
      - 10.6.0.0/24
      - 85.134.18.87/32
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
