apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: lennart-test-control-plane
spec:
  kubeadmConfigSpec:
    files:
      - path: /etc/sysctl.d/k8s.conf
        content: |
          net.ipv4.ip_forward=1
    preKubeadmCommands:
      # For updates only
      # - apt-get install -y systemd-container
      # - systemctl enable --now systemd-sysupdate
      - apt-get install -y conntrack socat
      # Install crictl
      - curl -sSL -o /tmp/crictl.tar.gz https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.30.0/crictl-v1.30.0-linux-amd64.tar.gz
      - tar --extract --file /tmp/crictl.tar.gz
      - mv crictl /usr/local/bin/
      # Folders where we store the raw files
      - mkdir -p /opt/extensions/crio
      - mkdir -p /opt/extensions/kubernetes
      # Folder where systemd-sysext will look for the images
      - mkdir -p /var/lib/extensions
      - curl -o /opt/extensions/crio/crio-1.28.4.raw -L https://github.com/flatcar/sysext-bakery/releases/download/latest/crio-1.28.4-x86-64.raw
      - curl -o /opt/extensions/kubernetes/kubernetes-v1.30.1.raw -L https://github.com/flatcar/sysext-bakery/releases/download/latest/kubernetes-v1.30.1-x86-64.raw
      - ln -s /opt/extensions/crio/crio-1.28.4.raw /var/lib/extensions/crio.raw
      - ln -s /opt/extensions/kubernetes/kubernetes-v1.30.1.raw /var/lib/extensions/kubernetes.raw
      - systemctl enable --now systemd-sysext
      - systemctl restart systemd-sysext
      # Make sure crio is running before continuingt o kubeadm init
      - systemctl enable --now crio
      # Apply sysctl settings (ip forwarding)
      - sysctl --system
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        criSocket: unix:///var/run/crio/crio.sock
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: "openstack:///'{{ instance_id }}'"
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        criSocket: unix:///var/run/crio/crio.sock
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: "openstack:///'{{ instance_id }}'"
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: lennart-test-sysext
  replicas: 1
  version: v1.30.1
