apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: lennart-test-control-plane
spec:
  kubeadmConfigSpec:
    files:
    - contentFrom:
        secret:
          key: ubuntu-install-k8s-pre-release.sh
          name: install-k8s
      path: /tmp/install-k8s.sh
      owner: root:root
      permissions: '0755'
    preKubeadmCommands:
    - /tmp/install-k8s.sh
    clusterConfiguration:
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: "openstack:///{{ v1.instance_id }}"
        name: '{{ v1.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: "openstack:///{{ v1.instance_id }}"
        name: '{{ v1.local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: lennart-test-plain
  replicas: 1
  version: v1.33.0
