apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: lennart-test-control-plane
spec:
  kubeadmConfigSpec:
    files:
    - contentFrom:
        secret:
          key: ubuntu-install-k8s-release-artifacts.sh
          name: install-k8s
      path: /tmp/install-k8s.sh
      owner: root:root
      permissions: '0755'
    # kube-vip static pod manifest for HA control plane VIP.
    # Uses ARP mode with leader election so the VIP (10.1.0.101) floats
    # between CP nodes. On the first node, kube-vip claims the VIP before
    # kubeadm init runs; on joining nodes it participates in leader election.
    # For Kubernetes >= 1.29 we mount super-admin.conf (full privileges)
    # to the path kube-vip expects (/etc/kubernetes/admin.conf).
    - content: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: kube-vip
          namespace: kube-system
        spec:
          containers:
          - name: kube-vip
            image: ghcr.io/kube-vip/kube-vip:v1.0.4
            imagePullPolicy: IfNotPresent
            args:
            - manager
            env:
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_interface
              value: ""
            - name: vip_subnet
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: svc_enable
              value: "false"
            - name: vip_ddns
              value: "false"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "5"
            - name: vip_renewdeadline
              value: "3"
            - name: vip_retryperiod
              value: "1"
            - name: address
              value: "10.1.0.101"
            securityContext:
              capabilities:
                add:
                - NET_ADMIN
                - NET_RAW
            volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
          hostAliases:
          - hostnames:
            - kubernetes
            ip: 127.0.0.1
          hostNetwork: true
          volumes:
          - hostPath:
              path: /etc/kubernetes/super-admin.conf
            name: kubeconfig
      path: /etc/kubernetes/manifests/kube-vip.yaml
      owner: root:root
      permissions: '0644'
    preKubeadmCommands:
    - /tmp/install-k8s.sh
    clusterConfiguration:
      controllerManager:
        extraArgs:
        - name: cloud-provider
          value: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
        - name: cloud-provider
          value: external
        - name: provider-id
          value: "openstack:///{{ v1.instance_id }}"
        name: '{{ v1.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
        - name: cloud-provider
          value: external
        - name: provider-id
          value: "openstack:///{{ v1.instance_id }}"
        name: '{{ v1.local_hostname }}'
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: OpenStackMachineTemplate
        name: lennart-test-cp
  replicas: 3
  version: v1.35.0
