apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: lennart-test-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: "openstack:///{{ v1.instance_id }}"
          name: '{{ v1.local_hostname }}'
      files:
      - contentFrom:
          secret:
            key: ubuntu-install-k8s-release-artifacts.sh
            name: install-k8s
        path: /tmp/install-k8s.sh
        owner: root:root
        permissions: '0755'
      preKubeadmCommands:
      - /tmp/install-k8s.sh
