apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: lennart-test-sysext
spec:
  template:
    spec:
      flavor: c4m12-est
      image:
        id: 19e017ae-2759-479c-90ac-a400a3f64678
        # filter:
        #   name: Ubuntu-24.04
      # rootVolume:
      #   sizeGiB: 100
      sshKeyName: lennart-ed25519
      # ports:
      #   - network:
      #       filter:
      #         name: metal3-ci-net
