---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: lennart-test
spec:
  apiServerLoadBalancer:
    allowedCIDRs:
    - 10.6.0.0/24
    - 91.150.49.195/32
    enabled: true
  bastion:
    enabled: true
    spec:
      flavor: 1C-2GB-50GB
      image:
        filter:
          name: Ubuntu 22.04 Jammy Jellyfish x86_64
      sshKeyName: lennart-ed25519
  externalNetwork:
    filter:
      name: ext-net
    # id: fba95253-5543-4078-b793-e2de58c31378
  identityRef:
    cloudName: lennart-test-fra1
    name: lennart-test-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Calico - BGP
      direction: ingress
      etherType: IPv4
      name: BGP (calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Calico IP-in-IP
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
    allowAllInClusterTraffic: false
  managedSubnets:
  - cidr: 10.6.0.0/24
    dnsNameservers:
    - 8.8.8.8
