---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: lennart-test-sysext
spec:
  template:
    spec:
      flavor: c4m4
      identityRef:
        cloudName: xerces-capo
        name: lennart-test-cloud-config
      image:
        id: 9cf21bd2-ad5b-4f98-8eaa-36c749c88015
        # filter:
        #   name: ubuntu-24.04
      rootVolume:
        sizeGiB: 100
      sshKeyName: lennart-ed25519
      # ports:
      #   - network:
      #       filter:
      #         name: metal3-ci-net
