apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-controlplane-plain
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: test-1-controlplane-template
      image:
        checksum: cb0ba1e5a579188fabab89a6745891ce8752aef926ffa70ec59b8570fbb7725e
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-workers-plain
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-1-workers-template
      image:
        checksum: cb0ba1e5a579188fabab89a6745891ce8752aef926ffa70ec59b8570fbb7725e
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404.raw
