apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-controlplane-v1-31-1
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      hostSelector:
        matchLabels:
          bmh-name: bmo-e2e-0
      automatedCleaningMode: metadata
      dataTemplate:
        name: test-1-controlplane-template
      image:
        checksum: aab4cbba9707d14c58931f6e9fb75736d5fe3df0f52a4e19c70609e11b5623af
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404-kube-v1.31.1.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-workers-v1-31-1
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-1-workers-template
      image:
        checksum: aab4cbba9707d14c58931f6e9fb75736d5fe3df0f52a4e19c70609e11b5623af
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404-kube-v1.31.1.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-controlplane-v1-30-1
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      hostSelector:
        matchLabels:
          bmh-name: bmo-e2e-0
      automatedCleaningMode: metadata
      dataTemplate:
        name: test-1-controlplane-template
      image:
        checksum: 8889e3ca8b1ce564ff753a5aa8d0967ce546fcfaab1b7e59fd0ae87e967b8dfc
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2204-kube-v1.30.1.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-workers-v1-30-1
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-1-workers-template
      image:
        checksum: 8889e3ca8b1ce564ff753a5aa8d0967ce546fcfaab1b7e59fd0ae87e967b8dfc
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2204-kube-v1.30.1.raw
