apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-controlplane-v1-31-1
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      hostSelector:
        matchLabels:
          bmh-name: bmo-e2e-0
      automatedCleaningMode: metadata
      dataTemplate:
        name: test-1-controlplane-template
      image:
        checksum: aab4cbba9707d14c58931f6e9fb75736d5fe3df0f52a4e19c70609e11b5623af
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404-kube-v1.31.1.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-workers-v1-31-1
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-1-workers-template
      image:
        checksum: aab4cbba9707d14c58931f6e9fb75736d5fe3df0f52a4e19c70609e11b5623af
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404-kube-v1.31.1.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-controlplane-v1-32-0
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      hostSelector:
        matchLabels:
          bmh-name: bmo-e2e-0
      automatedCleaningMode: metadata
      dataTemplate:
        name: test-1-controlplane-template
      image:
        checksum: 73633cbc90a31f2578ce7f36b1ba440e2791361d6a1813be0bfe60f132e66e56
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404-kube-v1.32.0.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-1-workers-v1-32-0
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-1-workers-template
      image:
        checksum: 73633cbc90a31f2578ce7f36b1ba440e2791361d6a1813be0bfe60f132e66e56
        checksumType: sha256
        format: raw
        url: http://192.168.222.1/ubuntu-2404-kube-v1.32.0.raw
