apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cni-crs.yaml
- cloud-provider-openstack-crs.yaml
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- files:
  - cloud-config-secret.yaml
  name: cloud-config
  namespace: default
  type: addons.cluster.x-k8s.io/resource-set

configmapGenerator:
- files:
  - calico.yaml
  name: calico
  namespace: default
- files:
  - cloud-provider-openstack.yaml
  name: cloud-provider-openstack
  namespace: default
