apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- cluster.yaml
- metal3cluster.yaml
- kcp.yaml
- metal3machinetemplate.yaml
- metal3datatemplate.yaml
- ippool.yaml
