apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- https://github.com/metal3-io/baremetal-operator/ironic-deployment/overlays/basic-auth_tls?ref=main

configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap
  behavior: create

patches:
  - path: ironic-patch.yaml

# Generate the necessary secrets:
secretGenerator:
- behavior: create
  envs:
  - ironic-htpasswd
  name: ironic-htpasswd
- behavior: create
  envs:
  - ironic-inspector-htpasswd
  name: ironic-inspector-htpasswd
- name: ironic-auth-config
  files:
  - auth-config=ironic-auth-config
- name: ironic-inspector-auth-config
  files:
  - auth-config=ironic-inspector-auth-config

replacements:
  # Replace IRONIC_HOST_IP in certificates with the PROVISIONING_IP from the configmap
  - source:
      kind: ConfigMap
      name: ironic-bmo-configmap
      fieldPath: .data.PROVISIONING_IP
    targets:
      - select:
          version: v1
          group: cert-manager.io
          kind: Certificate
          name:
        fieldPaths:
          - .spec.ipAddresses.0
