apiVersion: v1
kind: Service
metadata:
  labels:
    name: ironic
  name: ironic
spec:
  ports:
  - name: 6180-6180
    port: 6180
    protocol: TCP
    targetPort: 6180
  - name: 6385-6385
    port: 6385
    protocol: TCP
    targetPort: 6385
  selector:
    name: ironic
  type: ClusterIP
